config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'documents#new'

  resources :documents
  resources :imports
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :integration

  mount_uploader :attachment, ProductAttachmentUploader
end

app/models/integration.rb
class Integration < ApplicationRecord
  has_many :documents
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  rescue_from StandardError do |e|
    Rails.logger.debug ([e.message]+e.backtrace).join($/)
    render json: e.message, status: 500
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

  def new
    @document = Document.new
  end

  def create
    document = Document.new
    UploadDocumentService.call(document, document_params[:attachment])
    redirect_to root_url
  end

  private

  def document_params
    params.require(:document)
          .permit(:attachment)
  end
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController

  def index
    @integrations = Integration.all
  end

  def create
    UpdateProductsService.call(import_params[:integration_ids])
    redirect_to root_url
  end

  def import_params
    params.require(:import)
          .permit(integration_ids:[])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/integrations_helper.rb
module IntegrationsHelper
end

app/views/documents/new.html.erb
<% if flash[:error].present? %>
  <div class="error"><%= flash[:error] %></div>
<% end %>

<h3>upload file with products</h3>

<%= form_for @document, url: documents_path do |form| %>
  <%= form.file_field :attachment %>
  <%= form.submit 'Upload' %>
<% end %>
<%= link_to 'go to import', imports_url %>

app/views/imports/index.html.erb
<h3>Select integrations to import</h3>

<%= form_tag imports_path do %>
    <%  @integrations.each do |integration| %>
    <%= check_box_tag 'import[integration_ids][]', integration.id, false, :id => integration.id %>
        <%= integration.name %> 
    <% end %>
    <%= submit_tag 'Import!' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DataminerTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>